//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CakeStorManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputInfor
    {
        public int Id { get; set; }
        public int IdInput { get; set; }
        public string IdCake { get; set; }
        public int IdSuplier { get; set; }
        public int Count { get; set; }
        public double InputPrice { get; set; }
        public string Status { get; set; }
        public bool isDelete { get; set; }
    
        public virtual Cake Cake { get; set; }
        public virtual Input Input { get; set; }
        public virtual Suplier Suplier { get; set; }
    }
}
